services:
  app:
    build: .
    container_name: kapa-pdf-rag
    image: kapa-pdf-rag:latest
    ports:
      - "8501:8501"
    volumes:
      - ./app:/workspace/app
      - ./src:/workspace/src
      - ./data:/workspace/data
      - ./.env:/workspace/.env
    environment:
      - PYTHONPATH=/workspace
    env_file:
      - .env
    stdin_open: true
    tty: true
